### ISSUE TITLE
Failed to set mode balanced G15 5511

### ISSUE THREAD

**Issue by crazynitro** [AlexIII/tcc-g15#3] opened 2022-05-26 18:55 UTC
Hello, 

I've tried to launch your program on my Dell G15 5511, but it returns this error. What I can do?

![image](https://user-images.githubusercontent.com/106346492/170557099-37da43d6-bf60-413a-a5d6-4c5dd01bc595.png)

Thanks in advance

**Comment by AlexIII** [comment] 2022-05-27 05:06
Hi!
It seems the program cannot communicate with the WMI driver properly, it may be missing. Try reinstalling the original AWCC, then ran the program. After that you can remove these AWCC components:
- Alieanware CC Components
- Alieanware Command Center Suite
- Alieanware OC Controls
Everything else is needed for the program to function.
Feel free to report back if this doesn't help.

**Comment by AlexIII** [comment] 2022-06-01 04:25
Yes, there are some components of AWCC that are critical for my program to function. Try installing older versions of AWCC (I use the version from December, 2021 if I remember correctly).
After the successful installation, most of AWCC can be removed, so it doesn't even matter if they work or not.

**Comment by T7imal** [comment] 2023-04-14 07:02
![image](https://user-images.githubusercontent.com/100835834/231967819-ed79addb-29c4-4d0b-8c30-46f3a63379f3.png)

在我的G15 5511上也无法正常运行。我刚刚重装了AWCC，但还是产生了一样的错误。当前的AWCC版本为5.4.35.0_A00，Alienware OC Controls版本为1.3.68.1380_A01。

**Comment by crazynitro** [comment] 2023-04-14 07:31
Updating Visual C++ Runtime and using last AWCC, this is now "working". But setting a fan speed is doing nothing.

**Comment by AlexIII** [comment] 2023-04-14 07:43
Unfortunately I don't have a 5511 model to experiment on. I think for now we can consider it unsupported.
I would need some debug info in order to try to fix it.

As a first step, try running the program from the terminal. See https://github.com/AlexIII/tcc-g15#how-to-run-from-the-source

Report back with whatever error message will be in the terminal (if any).

**Comment by T7imal** [comment] 2023-04-15 14:07
![$C3 RY@@L8T@~MYVFFDKV2B](https://user-images.githubusercontent.com/100835834/232229244-0a17db52-96e2-478b-a1d6-ad4346814549.png)

**Comment by AlexIII** [comment] 2023-04-16 09:30
Ok, try running this code
```python
import wmi
awccClass = wmi.WMI(namespace="root\WMI").AWCCWmiMethodFunction
print(awccClass)
```

The expected output is something like this 

![image](https://user-images.githubusercontent.com/10047074/232289775-2203a465-51ff-4681-bfc4-5959f0dd414f.png)

**Comment by T7imal** [comment] 2023-04-16 10:03
Here is the full output：
```
[WMI, dynamic: ToInstance, provider("WmiProv"), Locale("MS\\0x409"), Description("WMI Function"), guid("{A70591CE-A997-11DA-B012-B622A1EF5492}")]
class AWCCWmiMethodFunction
{
        [key, read] string InstanceName;
        [read] boolean Active;
        [WmiMethodId(13), Implemented, read, write, Description("Return Overclocking Report.")] void Return_OverclockingReport([out] uint32 argr);
        [WmiMethodId(14), Implemented, read, write, Description("Set OCUIBIOS Control.")] void Set_OCUIBIOSControl([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(15), Implemented, read, write, Description("Clear OC FailSafe Flag.")] void Clear_OCFailSafeFlag([out] uint32 argr);       
        [WmiMethodId(19), Implemented, read, write, Description("Get Fan Sensors.")] void GetFanSensors([in] uint32 arg2, [out] uint32 argr);   
        [WmiMethodId(20), Implemented, read, write, Description("Thermal Information.")] void Thermal_Information([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(21), Implemented, read, write, Description("Thermal Control.")] void Thermal_Control([in] uint32 arg2, [out] uint32 argr); 
        [WmiMethodId(22), Implemented, read, write, Description("BIOS OC Control.")] void BIOSOCControl([in] uint32 arg2, [out] uint32 argr);   
        [WmiMethodId(23), Implemented, read, write, Description("MemoryOCControl.")] void MemoryOCControl([in] uint32 arg2, [out] uint32 argr); 
        [WmiMethodId(24), Implemented, read, write, Description("Set SW OC Status.")] void SetSWOCStatus([in] uint32 arg2, [out] uint32 argr);  
        [WmiMethodId(25), Implemented, read, write, Description("OC Default Value.")] void OCDefaultValue([in] uint32 arg2, [out] uint32 argr); 
        [WmiMethodId(26), Implemented, read, write, Description("System Information.")] void SystemInformation([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(28), Implemented, read, write, Description("Power Information.")] void PowerInformation([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(32), Implemented, read, write, Description("FW Update GPIO toggle.")] void FWUpdateGPIOtoggle([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(33), Implemented, read, write, Description("Read Total of GPIOs.")] void ReadTotalofGPIOs([out] uint32 argr);
        [WmiMethodId(34), Implemented, read, write, Description("Read GPIO pin Status.")] void ReadGPIOpPinStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(35), Implemented, read, write, Description("Read Chassis Color.")] void ReadChassisColor([out] uint32 argr);
        [WmiMethodId(36), Implemented, read, write, Description("Read Platform Properties.")] void ReadPlatformProperties([out] uint32 argr);   
        [WmiMethodId(37), Implemented, read, write, Description("Game Shift Status.")] void GameShiftStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(128), Implemented, read, write, Description("Caldera SW installation.")] void CalderaSWInstallation([out] uint32 argr);    
        [WmiMethodId(129), Implemented, read, write, Description("Caldera SW is released.")] void CalderaSWReleased([out] uint32 argr);
        [WmiMethodId(130), Implemented, read, write, Description("Caldera Connection Status.")] void CalderaConnectionStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(131), Implemented, read, write, Description("Surprise Unplugged Flag Status.")] void SurpriseUnpluggedFlagStatus([out] uint32 argr);
        [WmiMethodId(132), Implemented, read, write, Description("Clear Surprise Unplugged Flag.")] void ClearSurpriseUnpluggedFlag([out] uint32 argr);
        [WmiMethodId(133), Implemented, read, write, Description("Cancel Undock Request.")] void CancelUndockRequest([out] uint32 argr);        
        [WmiMethodId(135), Implemented, read, write, Description("Devices in Caldera.")] void DevicesInCaldera([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(136), Implemented, read, write, Description("Notify BIOS for SW ready to disconnect Caldera.")] void NotifyBIOSForSWReadyToDisconnectCaldera([out] uint32 argr);
        [WmiMethodId(160), Implemented, read, write, Description("Tobii SW installation.")] void TobiiSWinstallation([out] uint32 argr);
        [WmiMethodId(161), Implemented, read, write, Description("Tobii SW Released.")] void TobiiSWReleased([out] uint32 argr);
        [WmiMethodId(162), Implemented, read, write, Description("Tobii Camera Power Reset.")] void TobiiCameraPowerReset([out] uint32 argr);
        [WmiMethodId(163), Implemented, read, write, Description("Tobii Camera Power On.")] void TobiiCameraPowerOn([out] uint32 argr);
        [WmiMethodId(164), Implemented, read, write, Description("Tobii Camera Power Off.")] void TobiiCameraPowerOff([out] uint32 argr);
};
```

**Comment by AlexIII** [comment] 2023-04-16 11:33
Thank you for that info. It seems that the WMI interface is exactly the same as mine (on 5515), that's why there's no descriptive errors.
The DELL driver itself is refusing to change mode, returning an error. As to why this is happening, one can only guess...
Maybe there's some system component is missing or it's there's no sufficient rights.
Does the original AWCC software works (shows the current temp, etc.)? It uses the same interface, so it is indeed strange why one program works, but the other doesn't.
Unfortunately, I cannot offer any further analysis an the moment.

**Comment by T7imal** [comment] 2023-04-16 12:28
AWCC works very well, except that it can't show the correct RAM timings, which should be 20-20-20-42.

![image](https://user-images.githubusercontent.com/100835834/232309523-ed8fb9c6-30f0-4cb0-b57c-77ab902fa7a4.png)

All other functions work fine, including the fan speed control.

![image](https://user-images.githubusercontent.com/100835834/232309561-65176d6a-1ae5-40b3-85ed-4264f275339a.png)

Unfortunately I don't understand Python, otherwise I could help more.

**Comment by AlexIII** [comment] 2023-04-16 15:14
> Unfortunately I don't understand Python, 

The problem is, as I gathered, it's not python. Python here is just responsible for drawing a GUI over WMI (with is a part of dell driver) and that driver part does not want to talk to the python part for some reason (returning an error).

**Comment by crazynitro** [comment] 2023-04-16 16:02
> AWCC works very well, except that it can't show the correct RAM timings, which should be 20-20-20-42.
>
> All other functions work fine, including the fan speed control.
> 
> Unfortunately I don't understand Python, otherwise I could help more.

How fan control is working for you into AWCC? When setting up a new profile with fans at 100%, they keep going automatic.

![2023-04-16 17_58_43-Alienware Command Center](https://user-images.githubusercontent.com/106346492/232325255-2362e320-3a52-427f-a68c-e6db470a51d2.png)
![2023-04-16 17_59_05-Alienware Command Center](https://user-images.githubusercontent.com/106346492/232325262-b7e46490-0746-4d8a-a607-0949059b82d0.png)

**Comment by T7imal** [comment] 2023-04-17 04:23
> How fan control is working for you into AWCC?

Just like this.

![image](https://user-images.githubusercontent.com/100835834/232376984-8ef18685-99c0-44c4-9f9a-5bc88ec04319.png)

You need to press the link button, select the PC icon and confirm.

![image](https://user-images.githubusercontent.com/100835834/232377318-abc93522-1169-495d-b460-08abec148a24.png)

**Comment by cemkaya-mpi** [comment] 2023-06-04 19:26
I have the same issue on a Dell G15 5525. AWCC works. Here is the output of the code:
```
[WMI, dynamic: ToInstance, provider("WmiProv"), Locale("MS\\0x409"), Description("WMI Function"), guid("{A70591CE-A997-11DA-B012-B622A1EF5492}")]
class AWCCWmiMethodFunction
{
        [key, read] string InstanceName;
        [read] boolean Active;
        [WmiMethodId(13), Implemented, read, write, Description("Return Overclocking Report.")] void Return_OverclockingReport([out] uint32 argr);
        [WmiMethodId(14), Implemented, read, write, Description("Set OCUIBIOS Control.")] void Set_OCUIBIOSControl([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(15), Implemented, read, write, Description("Clear OC FailSafe Flag.")] void Clear_OCFailSafeFlag([out] uint32 argr);
        [WmiMethodId(19), Implemented, read, write, Description("Get Fan Sensors.")] void GetFanSensors([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(20), Implemented, read, write, Description("Thermal Information.")] void Thermal_Information([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(21), Implemented, read, write, Description("Thermal Control.")] void Thermal_Control([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(22), Implemented, read, write, Description("BIOS OC Control.")] void BIOSOCControl([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(23), Implemented, read, write, Description("MemoryOCControl.")] void MemoryOCControl([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(24), Implemented, read, write, Description("Set SW OC Status.")] void SetSWOCStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(25), Implemented, read, write, Description("OC Default Value.")] void OCDefaultValue([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(26), Implemented, read, write, Description("System Information.")] void SystemInformation([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(28), Implemented, read, write, Description("Power Information.")] void PowerInformation([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(32), Implemented, read, write, Description("FW Update GPIO toggle.")] void FWUpdateGPIOtoggle([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(33), Implemented, read, write, Description("Read Total of GPIOs.")] void ReadTotalofGPIOs([out] uint32 argr);
        [WmiMethodId(34), Implemented, read, write, Description("Read GPIO pin Status.")] void ReadGPIOpPinStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(35), Implemented, read, write, Description("Read Chassis Color.")] void ReadChassisColor([out] uint32 argr);
        [WmiMethodId(36), Implemented, read, write, Description("Read Platform Properties.")] void ReadPlatformProperties([out] uint32 argr);
        [WmiMethodId(37), Implemented, read, write, Description("Game Shift Status.")] void GameShiftStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(128), Implemented, read, write, Description("Caldera SW installation.")] void CalderaSWInstallation([out] uint32 argr);
        [WmiMethodId(129), Implemented, read, write, Description("Caldera SW is released.")] void CalderaSWReleased([out] uint32 argr);
        [WmiMethodId(130), Implemented, read, write, Description("Caldera Connection Status.")] void CalderaConnectionStatus([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(131), Implemented, read, write, Description("Surprise Unplugged Flag Status.")] void SurpriseUnpluggedFlagStatus([out] uint32 argr);
        [WmiMethodId(132), Implemented, read, write, Description("Clear Surprise Unplugged Flag.")] void ClearSurpriseUnpluggedFlag([out] uint32 argr);
        [WmiMethodId(133), Implemented, read, write, Description("Cancel Undock Request.")] void CancelUndockRequest([out] uint32 argr);
        [WmiMethodId(135), Implemented, read, write, Description("Devices in Caldera.")] void DevicesInCaldera([in] uint32 arg2, [out] uint32 argr);
        [WmiMethodId(136), Implemented, read, write, Description("Notify BIOS for SW ready to disconnect Caldera.")] void NotifyBIOSForSWReadyToDisconnectCaldera([out] uint32 argr);
        [WmiMethodId(160), Implemented, read, write, Description("Tobii SW installation.")] void TobiiSWinstallation([out] uint32 argr);
        [WmiMethodId(161), Implemented, read, write, Description("Tobii SW Released.")] void TobiiSWReleased([out] uint32 argr);
        [WmiMethodId(162), Implemented, read, write, Description("Tobii Camera Power Reset.")] void TobiiCameraPowerReset([out] uint32 argr);
        [WmiMethodId(163), Implemented, read, write, Description("Tobii Camera Power On.")] void TobiiCameraPowerOn([out] uint32 argr);
        [WmiMethodId(164), Implemented, read, write, Description("Tobii Camera Power Off.")] void TobiiCameraPowerOff([out] uint32 argr);
};
```

**Comment by AlexIII** [comment] 2023-06-05 05:59
@T7imal, @cemkaya-mpi 

Can you try running this test script?
This code will try to activate G-mode. If everything goes as planned then you should see simple message in the terminal `(0,)`. Your fans should up to max speed in 5 to 10 sec.
If something goes wrong, hope there's going to be an error message.

```
import wmi
awccClass = wmi.WMI(namespace="root\WMI").AWCCWmiMethodFunction
awcc = awccClass()[0]
Thermal_Control = getattr(awcc, 'Thermal_Control')
mode = 0xAB # G-mode
# mode = 0x97 # Balanced
mode_val = (mode << 8) | 1
res = Thermal_Control(mode_val)
print(res)
```

Again, the code requires admin privileges.

**Comment by T7imal** [comment] 2023-06-05 08:31
> This code will try to activate G-mode. If everything goes as planned then you should see simple message in the terminal `(0,)`. Your fans should spin up to max speed in 5 to 10 sec.

It works! However, I also tried to set `mode` to `0x97`, the terminal returns `(-1,)`, and it seems having no effect. The fans still ran at 100% speed. 
Considering that the issue is "Failed to set mode balanced", maybe **the value representing the balanced mode is different in 5511 and 5515.**
I wonder how to find out the value representing balanced mode on my computer.

**Comment by cemkaya-mpi** [comment] 2023-06-05 09:19
Also the same for me, the code runs G-mode without problems.

**Comment by AlexIII** [comment] 2023-06-05 10:17
@T7imal nice catch! Maybe you're on to something.
@cemkaya-mpi please also try to uncomment 'Balanced' mode line `mode = 0x97`.

`(-1,)` means the driver returned an error.

Here's other possible values for `mode` variable for the script above, that I've recovered from disassembling the original software.
Please try it.

```
public enum ThermalMode
{
    Custom = 0,                     // ok
    Quiet = 150,
    Balanced = 151,                 // ok
    Performance = 152,
    FullSpeed = 153,
    USTT_Balanced = 160,
    USTT_Performance = 161,
    USTT_Cool = 162,
    USTT_Quiet = 163,
    USTT_FullSpeed = 164,
    USTT_BatterySaver = 165,
    G_Mode = 171                    // ok
}
```

**Comment by cemkaya-mpi** [comment] 2023-06-05 10:39
Among these, Custom, USTT_Balanced, USTT_Performance, USTT_Quiet, USTT_FullSpeed, USTT_BatterySaver and G_Mode work.

**Comment by AlexIII** [comment] 2023-06-05 10:44
Very interesting. It seems your laptop uses "USTT" modes, while my 5515 report an error for _any_ "USTT" mode.
Maybe we can get away by just testing whichever of `Balanced` and `USTT_Balanced` works and simply use that.

Last test then.
First set G-mode with the script, wait for the fans to spin up, then set `USTT_Balanced` (160). Will fans slow down to their normal speed?

**Comment by cemkaya-mpi** [comment] 2023-06-05 10:45
After replacing 0x97 with160 on line 13 of AWCCWmiWrapper.py, the GUI shows up. However, I am not sure if the application works as intended, because in custom mode, when I set the fan speed to 0, the fans are still at 2500rpm/2200rpm.

**Comment by cemkaya-mpi** [comment] 2023-06-05 10:46
> First set G-mode with the script, wait for the fans to spin up, then set USTT_Balanced (160). Will fans slow down to their normal speed?

Yes, the fans return to normal speed after going from G Mode to USTT_Balanced.

**Comment by AlexIII** [comment] 2023-06-05 10:48
>  in custom mode, when I set the fan speed to 0, the fans are still at 2500rpm/2200rpm.
That's normal. BIOS overtakes control over fans when it feels like the temp is too high. You need to cool down your laptop to ~40°C GPU/CPU, then the fans will stop.

**Comment by AlexIII** [comment] 2023-06-05 10:51
Ok, I will add the fix to the main code later today and write you back here

**Comment by T7imal** [comment] 2023-06-05 10:56
On 5511, mode 0, 160, 161, 162, 163, 171 works. there's a little difference from 5525, but I think it doesn't matter.
It seems that the application works well on my computer now too.

**Comment by AlexIII** [comment] 2023-06-05 11:19
@T7imal @cemkaya-mpi I made a patch, it's in the [dev branch](https://github.com/AlexIII/tcc-g15/tree/dev).

Please test it by running
```
python3 -m pip install -r ./requirements.txt
```
And then with admin privileges
```
python3 tcc-g15.py
```

Please also tell me exactly what laptop model do you have. Is it 551, 5525? I will put that info in the readme.

**Comment by T7imal** [comment] 2023-06-05 11:36
It works well on my 5511. Really appreciate it.

**Comment by AlexIII** [comment] 2023-06-05 11:53
I've made [release 1.4.0](https://github.com/AlexIII/tcc-g15/releases) that includes the fix.
Thank you guys for all your help!

**Closed** 2023-06-05 11:53 UTC
Labels: help wanted
